### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by andreasabel**

### CODE REVIEW

**Comment by Gabriella439** [comment]
I published the matching revision to Hackage

**Comment by alexfmpe** [comment]
@Gabriella439 looks like the mvc <1.2 bound never got a revision for 1.2.0. Only 1.1.2 builds with mvc >= 1.1

**Comment by alexfmpe** [comment]
Actually 1.2.0 doesn't contain https://github.com/Gabriella439/Haskell-MVC-Updates-Library/commit/47b31202b761439947ffbc89ec1c6854c1520819 so it doesn't work with foldl 1.1.x even though the bound says < 1.5

**Comment by Gabriella439** [comment]
Both issues should be fixed now

**Pull request merged**
